---
abstract: 'Convert a DOS Batch Script to an Executable'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  File::Remove: 1.42
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Alien::BatToExeConverter
name: Alien-BatToExeConverter
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::ShareDir: 1.00
  File::Which: 0.05
  IPC::Run3: 0.042
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
